// Mapeo de iconos de lucide-react a @heroicons/react
// Este archivo ayuda a encontrar los iconos equivalentes durante la migración

export const ICON_MAPPING: Record<string, { heroicon: string; path: 'outline' | 'solid' }> = {
  // Iconos comunes
  'Search': { heroicon: 'MagnifyingGlassIcon', path: 'outline' },
  'Home': { heroicon: 'HomeIcon', path: 'outline' },
  'User': { heroicon: 'UserIcon', path: 'outline' },
  'Users': { heroicon: 'UsersIcon', path: 'outline' },
  'UserPlus': { heroicon: 'UserPlusIcon', path: 'outline' },
  'Mail': { heroicon: 'EnvelopeIcon', path: 'outline' },
  'Phone': { heroicon: 'PhoneIcon', path: 'outline' },
  'PhoneIncoming': { heroicon: 'PhoneIcon', path: 'outline' },
  'PhoneOutgoing': { heroicon: 'PhoneIcon', path: 'outline' },
  'PhoneMissed': { heroicon: 'PhoneXMarkIcon', path: 'outline' },
  'Calendar': { heroicon: 'CalendarIcon', path: 'outline' },
  'Clock': { heroicon: 'ClockIcon', path: 'outline' },
  'Check': { heroicon: 'CheckIcon', path: 'outline' },
  'CheckCircle': { heroicon: 'CheckCircleIcon', path: 'outline' },
  'CheckCircle2': { heroicon: 'CheckCircleIcon', path: 'solid' },
  'X': { heroicon: 'XMarkIcon', path: 'outline' },
  'XCircle': { heroicon: 'XCircleIcon', path: 'outline' },
  'Edit': { heroicon: 'PencilIcon', path: 'outline' },
  'Edit2': { heroicon: 'PencilSquareIcon', path: 'outline' },
  'Trash2': { heroicon: 'TrashIcon', path: 'outline' },
  'Save': { heroicon: 'ArrowDownTrayIcon', path: 'outline' },
  'Download': { heroicon: 'ArrowDownTrayIcon', path: 'outline' },
  'Upload': { heroicon: 'ArrowUpTrayIcon', path: 'outline' },
  'ArrowLeft': { heroicon: 'ArrowLeftIcon', path: 'outline' },
  'ArrowRight': { heroicon: 'ArrowRightIcon', path: 'outline' },
  'ArrowUp': { heroicon: 'ArrowUpIcon', path: 'outline' },
  'ArrowDown': { heroicon: 'ArrowDownIcon', path: 'outline' },
  'ArrowUpDown': { heroicon: 'ArrowsUpDownIcon', path: 'outline' },
  'ChevronLeft': { heroicon: 'ChevronLeftIcon', path: 'outline' },
  'ChevronRight': { heroicon: 'ChevronRightIcon', path: 'outline' },
  'ChevronDown': { heroicon: 'ChevronDownIcon', path: 'outline' },
  'ChevronUp': { heroicon: 'ChevronUpIcon', path: 'outline' },
  'Plus': { heroicon: 'PlusIcon', path: 'outline' },
  'Minus': { heroicon: 'MinusIcon', path: 'outline' },
  'FileText': { heroicon: 'DocumentTextIcon', path: 'outline' },
  'FileCheck': { heroicon: 'DocumentCheckIcon', path: 'outline' },
  'File': { heroicon: 'DocumentIcon', path: 'outline' },
  'Image': { heroicon: 'PhotoIcon', path: 'outline' },
  'Shield': { heroicon: 'ShieldCheckIcon', path: 'outline' },
  'CreditCard': { heroicon: 'CreditCardIcon', path: 'outline' },
  'Settings': { heroicon: 'Cog6ToothIcon', path: 'outline' },
  'Settings2': { heroicon: 'CogIcon', path: 'outline' },
  'LogOut': { heroicon: 'ArrowRightOnRectangleIcon', path: 'outline' },
  'LogIn': { heroicon: 'ArrowLeftOnRectangleIcon', path: 'outline' },
  'Filter': { heroicon: 'FunnelIcon', path: 'outline' },
  'MapPin': { heroicon: 'MapPinIcon', path: 'outline' },
  'Flag': { heroicon: 'FlagIcon', path: 'outline' },
  'Star': { heroicon: 'StarIcon', path: 'outline' },
  'Building2': { heroicon: 'BuildingOffice2Icon', path: 'outline' },
  'DollarSign': { heroicon: 'CurrencyDollarIcon', path: 'outline' },
  'Activity': { heroicon: 'ChartBarIcon', path: 'outline' },
  'BarChart3': { heroicon: 'ChartBarIcon', path: 'outline' },
  'ExternalLink': { heroicon: 'ArrowTopRightOnSquareIcon', path: 'outline' },
  'AlertCircle': { heroicon: 'ExclamationCircleIcon', path: 'outline' },
  'AlertTriangle': { heroicon: 'ExclamationTriangleIcon', path: 'outline' },
  'Info': { heroicon: 'InformationCircleIcon', path: 'outline' },
  'Loader2': { heroicon: 'ArrowPathIcon', path: 'outline' },
  'RefreshCw': { heroicon: 'ArrowPathIcon', path: 'outline' },
  'Copy': { heroicon: 'DocumentDuplicateIcon', path: 'outline' },
  'Lock': { heroicon: 'LockClosedIcon', path: 'outline' },
  'Unlock': { heroicon: 'LockOpenIcon', path: 'outline' },
  'Eye': { heroicon: 'EyeIcon', path: 'outline' },
  'EyeOff': { heroicon: 'EyeSlashIcon', path: 'outline' },
  'MessageCircle': { heroicon: 'ChatBubbleLeftRightIcon', path: 'outline' },
  'MessageSquare': { heroicon: 'ChatBubbleLeftIcon', path: 'outline' },
  'Send': { heroicon: 'PaperAirplaneIcon', path: 'outline' },
  'List': { heroicon: 'ListBulletIcon', path: 'outline' },
  'LayoutGrid': { heroicon: 'Squares2X2Icon', path: 'outline' },
  'Grid3x3': { heroicon: 'Squares2X2Icon', path: 'outline' },
  'Menu': { heroicon: 'Bars3Icon', path: 'outline' },
  'Circle': { heroicon: 'XCircleIcon', path: 'outline' },
  'PenTool': { heroicon: 'PencilIcon', path: 'outline' },
  'Share2': { heroicon: 'ShareIcon', path: 'outline' },
  'Lightbulb': { heroicon: 'LightBulbIcon', path: 'outline' },
  'Sparkles': { heroicon: 'SparklesIcon', path: 'outline' },
  'Bot': { heroicon: 'CommandLineIcon', path: 'outline' },
  'GripVertical': { heroicon: 'EllipsisVerticalIcon', path: 'outline' },
  'LayoutDashboard': { heroicon: 'Squares2X2Icon', path: 'outline' },
  'Briefcase': { heroicon: 'BriefcaseIcon', path: 'outline' },
  'Key': { heroicon: 'KeyIcon', path: 'outline' },
  'UserCheck': { heroicon: 'UserIcon', path: 'outline' },
  'UserX': { heroicon: 'UserIcon', path: 'outline' },
  'UserCog': { heroicon: 'UserIcon', path: 'outline' }, // No hay equivalente exacto
  'History': { heroicon: 'ClockIcon', path: 'outline' },
  'PhoneCall': { heroicon: 'PhoneIcon', path: 'outline' },
  'TrendingUp': { heroicon: 'ArrowTrendingUpIcon', path: 'outline' },
  // Iconos adicionales encontrados
  'MoreHorizontal': { heroicon: 'EllipsisHorizontalIcon', path: 'outline' },
  'BookOpen': { heroicon: 'BookOpenIcon', path: 'outline' },
  'Play': { heroicon: 'PlayIcon', path: 'outline' },
  'Pause': { heroicon: 'PauseIcon', path: 'outline' },
  'CheckSquare': { heroicon: 'CheckSquareIcon', path: 'outline' },
  'StickyNote': { heroicon: 'DocumentTextIcon', path: 'outline' },
  'Bell': { heroicon: 'BellIcon', path: 'outline' },
  'Euro': { heroicon: 'CurrencyEuroIcon', path: 'outline' },
  'Link': { heroicon: 'LinkIcon', path: 'outline' },
  'Pencil': { heroicon: 'PencilIcon', path: 'outline' },
  'Globe': { heroicon: 'GlobeAltIcon', path: 'outline' },
  'Code': { heroicon: 'CodeBracketIcon', path: 'outline' },
  'Server': { heroicon: 'ServerIcon', path: 'outline' },
};

// Helper para obtener el import correcto
export function getHeroIconImport(lucideIcon: string): string {
  const mapping = ICON_MAPPING[lucideIcon];
  if (!mapping) {
    console.warn(`No mapping found for icon: ${lucideIcon}`);
    return '';
  }
  return `@heroicons/react/24/${mapping.path}`;
}
